name: Unit Tests
on: 
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: |
          poetry install --no-root --no-interaction

      - name: Run lint
        run: |
          poetry run inv lint

      - name: Run test suite
        run: |
          poetry run inv tests
